// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *ActivateAllInboundsResponseDtoResponse) setDefaults() {
	{
		val := ActivateAllInboundsResponseDtoResponseStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := int(0)
		s.TrafficLimitBytes.SetTo(val)
	}
	{
		val := ActivateAllInboundsResponseDtoResponseTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BulkAllUpdateUsersRequestDto) setDefaults() {
	{
		val := BulkAllUpdateUsersRequestDtoStatus("ACTIVE")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BulkDeleteHostsResponseDtoResponseItem) setDefaults() {
	{
		val := bool(false)
		s.AllowInsecure.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := BulkDeleteHostsResponseDtoResponseItemSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BulkDeleteUsersByStatusRequestDto) setDefaults() {
	{
		val := BulkDeleteUsersByStatusRequestDtoStatus("ACTIVE")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BulkDisableHostsResponseDtoResponseItem) setDefaults() {
	{
		val := bool(false)
		s.AllowInsecure.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := BulkDisableHostsResponseDtoResponseItemSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BulkEnableHostsResponseDtoResponseItem) setDefaults() {
	{
		val := bool(false)
		s.AllowInsecure.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := BulkEnableHostsResponseDtoResponseItemSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BulkUpdateUsersRequestDtoFields) setDefaults() {
	{
		val := BulkUpdateUsersRequestDtoFieldsStatus("ACTIVE")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateHostRequestDto) setDefaults() {
	{
		val := bool(false)
		s.AllowInsecure.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := CreateHostRequestDtoSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateHostResponseDtoResponse) setDefaults() {
	{
		val := bool(false)
		s.AllowInsecure.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := CreateHostResponseDtoResponseSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateNodeRequestDto) setDefaults() {
	{
		val := bool(false)
		s.IsTrafficTrackingActive.SetTo(val)
	}
	{
		val := string("XX")
		s.CountryCode.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateUserRequestDto) setDefaults() {
	{
		val := CreateUserRequestDtoStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := CreateUserRequestDtoTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy = val
	}
}

// setDefaults set default value of fields.
func (s *DisableUserResponseDtoResponse) setDefaults() {
	{
		val := DisableUserResponseDtoResponseStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := int(0)
		s.TrafficLimitBytes.SetTo(val)
	}
	{
		val := DisableUserResponseDtoResponseTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EnableUserResponseDtoResponse) setDefaults() {
	{
		val := EnableUserResponseDtoResponseStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := int(0)
		s.TrafficLimitBytes.SetTo(val)
	}
	{
		val := EnableUserResponseDtoResponseTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetAllHostsResponseDtoResponseItem) setDefaults() {
	{
		val := bool(false)
		s.AllowInsecure.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := GetAllHostsResponseDtoResponseItemSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetOneHostResponseDtoResponse) setDefaults() {
	{
		val := bool(false)
		s.AllowInsecure.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := GetOneHostResponseDtoResponseSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetUserByTagResponseDtoResponseItem) setDefaults() {
	{
		val := GetUserByTagResponseDtoResponseItemStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := int(0)
		s.TrafficLimitBytes.SetTo(val)
	}
	{
		val := GetUserByTagResponseDtoResponseItemTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetUserByUuidResponseDtoResponse) setDefaults() {
	{
		val := GetUserByUuidResponseDtoResponseStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := int(0)
		s.TrafficLimitBytes.SetTo(val)
	}
	{
		val := GetUserByUuidResponseDtoResponseTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ResetUserTrafficResponseDtoResponse) setDefaults() {
	{
		val := ResetUserTrafficResponseDtoResponseStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := int(0)
		s.TrafficLimitBytes.SetTo(val)
	}
	{
		val := ResetUserTrafficResponseDtoResponseTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RevokeUserSubscriptionResponseDtoResponse) setDefaults() {
	{
		val := RevokeUserSubscriptionResponseDtoResponseStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := int(0)
		s.TrafficLimitBytes.SetTo(val)
	}
	{
		val := RevokeUserSubscriptionResponseDtoResponseTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SetInboundToManyHostsResponseDtoResponseItem) setDefaults() {
	{
		val := bool(false)
		s.AllowInsecure.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := SetInboundToManyHostsResponseDtoResponseItemSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SetPortToManyHostsResponseDtoResponseItem) setDefaults() {
	{
		val := bool(false)
		s.AllowInsecure.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := SetPortToManyHostsResponseDtoResponseItemSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateHostResponseDtoResponse) setDefaults() {
	{
		val := bool(false)
		s.AllowInsecure.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDisabled.SetTo(val)
	}
	{
		val := UpdateHostResponseDtoResponseSecurityLayer("DEFAULT")
		s.SecurityLayer.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateUserRequestDto) setDefaults() {
	{
		val := UpdateUserRequestDtoStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := UpdateUserRequestDtoTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UserDto) setDefaults() {
	{
		val := UserDtoStatus("ACTIVE")
		s.Status.SetTo(val)
	}
	{
		val := int(0)
		s.TrafficLimitBytes.SetTo(val)
	}
	{
		val := UserDtoTrafficLimitStrategy("NO_RESET")
		s.TrafficLimitStrategy.SetTo(val)
	}
}
