// Code generated by ogen, DO NOT EDIT.
package api

type AuthControllerLoginRes interface {
	authControllerLoginRes()
}

type AuthControllerRegisterRes interface {
	authControllerRegisterRes()
}

type HostsControllerDeleteHostRes interface {
	hostsControllerDeleteHostRes()
}

type SubscriptionsControllerGetSubscriptionByUsernameRes interface {
	subscriptionsControllerGetSubscriptionByUsernameRes()
}

type UsersControllerActivateAllInboundsRes interface {
	usersControllerActivateAllInboundsRes()
}

type UsersControllerDeleteUserRes interface {
	usersControllerDeleteUserRes()
}

type UsersControllerDisableUserRes interface {
	usersControllerDisableUserRes()
}

type UsersControllerEnableUserRes interface {
	usersControllerEnableUserRes()
}

type UsersControllerGetUserByShortUuidRes interface {
	usersControllerGetUserByShortUuidRes()
}

type UsersControllerGetUserBySubscriptionUuidRes interface {
	usersControllerGetUserBySubscriptionUuidRes()
}

type UsersControllerGetUserByTelegramIdRes interface {
	usersControllerGetUserByTelegramIdRes()
}

type UsersControllerGetUserByUsernameRes interface {
	usersControllerGetUserByUsernameRes()
}

type UsersControllerGetUserByUuidRes interface {
	usersControllerGetUserByUuidRes()
}

type UsersControllerGetUsersByEmailRes interface {
	usersControllerGetUsersByEmailRes()
}

type UsersControllerGetUsersByTagRes interface {
	usersControllerGetUsersByTagRes()
}

type UsersControllerResetUserTrafficRes interface {
	usersControllerResetUserTrafficRes()
}

type UsersControllerRevokeUserSubscriptionRes interface {
	usersControllerRevokeUserSubscriptionRes()
}

type UsersStatsControllerGetUserUsageByRangeRes interface {
	usersStatsControllerGetUserUsageByRangeRes()
}

type XrayConfigControllerGetConfigRes interface {
	xrayConfigControllerGetConfigRes()
}

type XrayConfigControllerUpdateConfigRes interface {
	xrayConfigControllerUpdateConfigRes()
}
